<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>md</string>
		<string>ycmd</string>
		<string>mdown</string>
		<string>mkdown</string>
		<string>markdn</string>
		<string>markdown</string>
		<string>ycmarkdown</string>
	</array>
	<key>name</key>
	<string>SCP-YC Markdown</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>^#{1,6} .+$</string>
			<key>name</key>
			<string>title</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;=\*\*\*)[^\*]+?(?=\*\*\*)</string>
			<key>name</key>
			<string>bold-italic</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;=\*\*)[^\*]+?(?=\*\*)</string>
			<key>name</key>
			<string>bold</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;=\*)[^\*]+?(?=\*[^\*])</string>
			<key>name</key>
			<string>italic</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;=~~).+?(?=~~)</string>
			<key>name</key>
			<string>del</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\*\*\*</string>
			<key>name</key>
			<string>bold-italic.symbol</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\*\*</string>
			<key>name</key>
			<string>bold.symbol</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\*(?=[^\*])</string>
			<key>name</key>
			<string>italic.symbol</string>
		</dict>
		<dict>
			<key>match</key>
			<string>~~</string>
			<key>name</key>
			<string>del.symbol</string>
		</dict>
		<dict>
			<key>match</key>
			<string>```</string>
			<key>name</key>
			<string>blockquote</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\[---\]</string>
			<key>name</key>
			<string>folder</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\[\+\] .+$</string>
			<key>name</key>
			<string>folder-info</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\[-\] .+$</string>
			<key>name</key>
			<string>folder-info</string>
		</dict>
		<dict>
			<key>match</key>
			<string>.+：</string>
			<key>name</key>
			<string>thead</string>
		</dict>
		<dict>
			<key>match</key>
			<string>!\[.*?\]</string>
			<key>name</key>
			<string>img.value</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\[.*?\]</string>
			<key>name</key>
			<string>link.value</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\(.*?\)</string>
			<key>name</key>
			<string>link.href</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.Markdown</string>
	<key>uuid</key>
	<string>896b578c-3243-432f-9db4-b08ea1d5055e</string>
</dict>
</plist>
